# Generated by Django 4.2.3 on 2023-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Make things happen, preferebaly good.', max_length=140),
        ),
    ]
